version: '2'

services:
  nginx:
    image: accent/nginx-uwsgi-proxy:latest
    volumes:
    - media-volume:/www/media
    - static-volume:/www/static
    depends_on:
    - app
    ports:
    - "80:80"
  app:
    build:
      context: .
    environment: 
    - DJANGO_SETTINGS_MODULE=app.settings
    - ALLOWED_HOSTS=*
    - RDS_HOSTNAME=db
    - RDS_PORT=5432
    - RDS_DB_NAME=postgres
    - RDS_USERNAME=postgres
    - RDS_PASSWORD=password
    volumes:
    - ./src:/app
    - media-volume:/app/public/media
    - static-volume:/app/public/static
    depends_on:
    - db
    - redis
    - mail
    ports:
    - "8000:8000"
  db:
    image: postgres:9.6
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=postgres
    - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
    - ./.postgres:/var/lib/postgresql/data/pgdata
    ports:
    - "5432:5432"
  redis:
    image: redis:alpine
  mail:
    image: mailhog/mailhog
    expose:
    - "1025"
    ports:
    - "8025:8025"

volumes:
  media-volume:
  static-volume: