version: '2'

services:
  app:
    build:
      context: .
      args:
      - REQUIREMENTS_FILE=/requirements/dev.txt
    environment:
    - DJANGO_SETTINGS_MODULE=app.settings
    - DEV_MODE=on
    - ALLOWED_HOSTS=*
    - RDS_HOSTNAME=db
    - RDS_PORT=5432
    - RDS_DB_NAME=postgres
    - RDS_USERNAME=postgres
    - RDS_PASSWORD=password
    - DJANGO_MANAGEPY_COLLECTSTATIC=off
    volumes:
    - ./src:/app
    depends_on:
    - db
    - redis
    - mail
    ports:
    - "8000:8000"
    command: ['python', 'manage.py', 'runserver', '0.0.0.0:8000']
  db:
    image: postgres:9.6
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=postgres
    - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
    - ./.postgres:/var/lib/postgresql/data/pgdata
    ports:
    - "5432:5432"
  redis:
    image: redis:alpine
  mail:
    image: mailhog/mailhog
    expose:
    - "1025"
    ports:
    - "8025:8025"