"""user_email

Revision ID: 133edc5f71e2
Revises: b5fceff3ef8a
Create Date: 2019-03-27 21:02:14.292186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '133edc5f71e2'
down_revision = 'b5fceff3ef8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
