version: '2'

services:
  app:
    build:
      context: .
      args:
      - REQUIREMENTS_FILE=/requirements/dev.txt
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/appdb
      - DEBUG=True
      # - SENTRY_DSN=https://44aeb04e7ba84ea782ba801e8f0da4ff@sentry.io/1427654
    volumes:
    - ./src:/app
    depends_on:
    - db
    ports:
    - "8000:8000"
    command: ['uvicorn', '--host', '0.0.0.0', '--port', '8000', '--reload', 'app:app']
  db:
    image: postgres:9.6
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=appdb
    - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
    - ./.postgres:/var/lib/postgresql/data/pgdata
    ports:
    - "5432:5432"